### ISSUE TITLE
Sites Avaliados 

### ISSUE THREAD

**Issue by LeticiaAires** [Interacao-Humano-Computador/2022.1-Faculdade-de-Arquitetura-e-Urbanismo#4]
Desenvolvimento de documentação referente aos sites avaliados.

# Tarefas
- [x]  Incluir corpo do texto
- [x] Incluir referências
- [x] Incluir versionamento
- [x] Incluir revisor

# Critérios de aceitação
- [x] Ter sido revisado
- [x] Incluir na branch development

**Comment by mc-gomes** [comment]
No tópico de ferramentas não aparecem as imagens dos ícones das ferramentas utilizadas
